##
## References:
## 1. [GitHub, Camunda, Getting started](https://github.com/camunda/camunda-platform-get-started)
##

server:
  servlet:
    context-path: /trip
  port: 8085

spring:
  application:
    name: trip-flow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgres-service:5432/testdb"
#    url: "jdbc:postgresql://172.21.213.195:55432/camunda"
    username: postgres
    password: password
    hikari:
      connection-timeout: 5000
  flyway:
    schemas: public
    create-schemas: true
    url: jdbc:postgresql://postgres-service:5432/testdb
    user: postgres
    password: password
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

zeebe:
  client:
    broker:
      gateway-address: camunda-platform-zeebe-gateway:26500
#      gateway-address: localhost:26500
    #      gateway-address: 172.21.213.195:26500
    security:
      plaintext: true

logging:
  level:
    com.github.tripflow: debug
    com.github.tripflow.infrastructure.adapter.web.LocalDispatcherServlet: info
    org.springframework:
      data.jdbc: info
      jdbc: info
      security: info

tripflow:
  task-look-up-max-retries: 5
  task-look-up-backoff-interval-millis: 250
  credit-limit:
    customer1: 500
    customer2: 400